'use client';

import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Modal } from '@/components/ui/modal';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { useToast } from '@/components/ui/toast';
import type { PresentationType } from '@/types/database';

interface SessionOption {
  id: string;
  name: string;
}

interface ApplicationOption {
  id: string;
  userName: string;
  roleName: string | null;
}

interface PresentationFormProps {
  open: boolean;
  onClose: () => void;
  castingId: string;
  sessions: SessionOption[];
  applications: ApplicationOption[];
  onSuccess: () => void;
}

const TYPE_OPTIONS = [
  { value: 'live', label: 'Live (auto-updating from sessions)' },
  { value: 'custom', label: 'Custom (select individual talent)' },
];

export function PresentationForm({ open, onClose, castingId, sessions, applications, onSuccess }: PresentationFormProps) {
  const [name, setName] = useState('');
  const [type, setType] = useState<PresentationType>('custom');
  const [password, setPassword] = useState('');
  const [expiresAt, setExpiresAt] = useState('');
  const [selectedSessionIds, setSelectedSessionIds] = useState<string[]>([]);
  const [selectedApplicationIds, setSelectedApplicationIds] = useState<string[]>([]);
  const [saving, setSaving] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const supabase = createClient();
  const { toast } = useToast();

  function validate(): boolean {
    const errs: Record<string, string> = {};
    if (!name.trim()) errs.name = 'Name is required';
    if (type === 'live' && selectedSessionIds.length === 0) errs.sessions = 'Select at least one session';
    if (type === 'custom' && selectedApplicationIds.length === 0) errs.applications = 'Select at least one talent';
    setErrors(errs);
    return Object.keys(errs).length === 0;
  }

  function toggleSession(id: string) {
    setSelectedSessionIds((prev) =>
      prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
    );
  }

  function toggleApplication(id: string) {
    setSelectedApplicationIds((prev) =>
      prev.includes(id) ? prev.filter((a) => a !== id) : [...prev, id]
    );
  }

  async function handleSubmit() {
    if (!validate()) return;
    setSaving(true);

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) { toast('Not authenticated', 'error'); setSaving(false); return; }

    // Step 1: Insert presentation (access_token auto-generated by DB)
    const { data: presentation, error: insertErr } = await supabase
      .from('presentations')
      .insert({
        casting_call_id: castingId,
        name: name.trim(),
        type,
        password: password.trim() || null,
        expires_at: expiresAt || null,
        is_active: true,
        allow_feedback: false,
        created_by: user.id,
      })
      .select('id')
      .single();

    if (insertErr || !presentation) {
      toast(insertErr?.message ?? 'Failed to create presentation', 'error');
      setSaving(false);
      return;
    }

    // Step 2: Insert junction records
    if (type === 'live' && selectedSessionIds.length > 0) {
      const rows = selectedSessionIds.map((sessionId, idx) => ({
        presentation_id: presentation.id,
        session_id: sessionId,
        sort_order: idx,
      }));
      const { error: sessErr } = await supabase.from('presentation_sessions').insert(rows);
      if (sessErr) {
        toast('Presentation created but failed to link sessions', 'error');
        setSaving(false);
        onSuccess();
        return;
      }
    }

    if (type === 'custom' && selectedApplicationIds.length > 0) {
      const rows = selectedApplicationIds.map((appId, idx) => ({
        presentation_id: presentation.id,
        application_id: appId,
        sort_order: idx,
      }));
      const { error: itemErr } = await supabase.from('presentation_items').insert(rows);
      if (itemErr) {
        toast('Presentation created but failed to add talent', 'error');
        setSaving(false);
        onSuccess();
        return;
      }
    }

    toast(`Presentation "${name.trim()}" created`, 'success');
    setSaving(false);
    onSuccess();
    onClose();
  }

  const selectionList = type === 'live' ? sessions : applications;
  const hasSelections = type === 'live' ? selectedSessionIds.length > 0 : selectedApplicationIds.length > 0;

  return (
    <Modal open={open} onClose={onClose} title="New Presentation" className="max-w-lg">
      <div className="space-y-4 pt-2">
        <Input
          id="presName"
          label="Name"
          placeholder="e.g. Client Review R1"
          value={name}
          onChange={(e) => setName(e.target.value)}
          error={errors.name}
          required
        />

        <Select
          id="presType"
          label="Type"
          options={TYPE_OPTIONS}
          value={type}
          onChange={(e) => setType(e.target.value as PresentationType)}
        />

        <div className="grid gap-4 sm:grid-cols-2">
          <Input
            id="presPassword"
            label="Password (optional)"
            type="password"
            placeholder="Leave blank for no password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <Input
            id="presExpiry"
            label="Expiry (optional)"
            type="date"
            value={expiresAt}
            onChange={(e) => setExpiresAt(e.target.value)}
          />
        </div>

        {/* Selection list */}
        <div className="space-y-2">
          <p className="text-sm font-medium text-foreground">
            {type === 'live' ? 'Sessions' : 'Talent'} ({type === 'live' ? selectedSessionIds.length : selectedApplicationIds.length} selected)
          </p>

          {selectionList.length === 0 ? (
            <div className="rounded-lg border-2 border-dashed border-border p-4 text-center text-sm text-muted-foreground">
              {type === 'live' ? 'No sessions found for this casting.' : 'No applications found for this casting.'}
            </div>
          ) : (
            <div className="max-h-48 overflow-y-auto rounded-lg border border-border">
              {type === 'live'
                ? sessions.map((s) => (
                    <label key={s.id} className="flex cursor-pointer items-center gap-3 border-b border-border px-3 py-2 last:border-b-0 hover:bg-muted/50">
                      <Checkbox
                        checked={selectedSessionIds.includes(s.id)}
                        onChange={() => toggleSession(s.id)}
                      />
                      <span className="text-sm text-foreground">{s.name}</span>
                    </label>
                  ))
                : applications.map((a) => (
                    <label key={a.id} className="flex cursor-pointer items-center gap-3 border-b border-border px-3 py-2 last:border-b-0 hover:bg-muted/50">
                      <Checkbox
                        checked={selectedApplicationIds.includes(a.id)}
                        onChange={() => toggleApplication(a.id)}
                      />
                      <span className="flex-1 text-sm text-foreground">{a.userName}</span>
                      {a.roleName && <span className="text-xs text-muted-foreground">{a.roleName}</span>}
                    </label>
                  ))
              }
            </div>
          )}
          {errors.sessions && <p className="text-sm text-destructive">{errors.sessions}</p>}
          {errors.applications && <p className="text-sm text-destructive">{errors.applications}</p>}
        </div>

        <div className="flex justify-end gap-3 border-t border-border pt-4">
          <Button variant="ghost" onClick={onClose} disabled={saving}>Cancel</Button>
          <Button onClick={handleSubmit} loading={saving} disabled={saving || !name.trim() || !hasSelections}>
            Create Presentation
          </Button>
        </div>
      </div>
    </Modal>
  );
}
